MVC_Music/Models/Musician.cs
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Security.AccessControl;
using System.Xml.Linq;

namespace MVC_Music.Models
{
    public class Musician : Auditable, IValidatableObject
    {
        public int ID { get; set; }

        [Display(Name = "Musician")]
        public string FullName
        {
            get
            {
                return FirstName
                    + (string.IsNullOrEmpty(MiddleName) ? " " :
                        (" " + (char?)MiddleName[0] + ". ").ToUpper())
                    + LastName;
            }
        }

        [Display(Name = "Musician")]
        public string FormalName
        {
            get
            {
                return LastName + ", " + FirstName
                    + (string.IsNullOrEmpty(MiddleName) ? "" :
                        (" " + (char?)MiddleName[0] + ".").ToUpper());
            }
        }

        public int Age
        {
            get
            {
                DateTime today = DateTime.Today;
                int a = today.Year - DOB.Year
                    - ((today.Month < DOB.Month || (today.Month == DOB.Month && today.Day < DOB.Day) ? 1 : 0));
                return a; /*Note: You could add .PadLeft(3) but spaces disappear in a web page. */
            }
        }

        [Display(Name = "SIN")]
        public string SINFormatted
        {
            get
            {
                return SIN.Substring(0, 3) + "-" + SIN.Substring(3, 3) + "-" + SIN.Substring(6, 3);
            }
        }

        [Display(Name = "Phone")]
        public string PhoneFormatted
        {
            get
            {
                return "(" + Phone.Substring(0, 3) + ") " + Phone.Substring(3, 3) + "-" + Phone[6..];
            }
        }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "You cannot leave the first name blank.")]
        [StringLength(30, ErrorMessage = "First name cannot be more than 30 characters long.")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        [StringLength(30, ErrorMessage = "Middle name cannot be more than 30 characters long.")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "You cannot leave the last name blank.")]
        [StringLength(50, ErrorMessage = "Last name cannot be more than 50 characters long.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Phone number is required.")]
        [RegularExpression("^\\d{10}$", ErrorMessage = "Please enter a valid 10-digit phone number (no spaces).")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(10)]
        public string Phone { get; set; }

        [Required(ErrorMessage = "You must enter the Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DOB { get; set; }

        [Required(ErrorMessage = "You cannot leave the SIN blank.")]
        [RegularExpression("^\\d{9}$", ErrorMessage = "The SIN must be exactly 9 numeric digits.")]
        [StringLength(9)]//DS Note: we only include this to limit the size of the database field to 10
        public string SIN { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        public MusicianPhoto MusicianPhoto { get; set; }

        public MusicianThumbnail MusicianThumbnail { get; set; }

        [Display(Name = "Primary Instrument")]
        [Required(ErrorMessage = "You must select the principal instrument the musician plays.")]
        public int InstrumentID { get; set; }

        [Display(Name = "Primary Instrument")]
        public Instrument Instrument { get; set; }

        [Display(Name = "All Instruments")]
        public ICollection<Play> Plays { get; set; } = new HashSet<Play>();

        [Display(Name = "Documents")]
        public ICollection<MusicianDocument> MusicianDocuments { get; set; } = new HashSet<MusicianDocument>();

        [Display(Name = "All Performances")]
        public ICollection<Performance> Performances { get; set; } = new HashSet<Performance>();

      

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DOB > DateTime.Today)
            {
                yield return new ValidationResult("Date of Birth cannot be in the future.", new[] { "DOB" });
            }
            else if (Age < 7)
            {
                yield return new ValidationResult("Musician must be at least 7 years old.", new[] { "DOB" });
            }
        }
    }
}

MVC_Music/Controllers/MusiciansController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using MVC_Music.Data;
using MVC_Music.Models;
using MVC_Music.Utilities;
using MVC_Music.ViewModels;
using NuGet.Protocol;
using OfficeOpenXml.Style;
using OfficeOpenXml;
using SkiaSharp;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;

namespace MVC_Music.Controllers
{
    [Authorize]
    public class MusiciansController : CustomControllers.ElephantController
    {
        private readonly MusicContext _context;

        public MusiciansController(MusicContext context)
        {
            _context = context;
        }

        // GET: Musicians
        public async Task<IActionResult> Index(string sortDirectionCheck, string sortFieldID, string SearchName, string SearchPhone, int? InstrumentID, int? OtherInstrumentID,
            int? page, int? pageSizeID, string actionButton, string sortDirection = "asc", string sortField = "Musician")
        {
            //Clear the sort/filter/paging URL Cookie for Controller
            CookieHelper.CookieSet(HttpContext, ControllerName() + "URL", "", -1);

            //Change colour of the button when filtering by setting this default
            ViewData["Filtering"] = "btn-outline-primary";
            //and then in each "test" for filtering, add ViewData["Filtering"] = "btn-danger" if true;

            PopulateDropDownLists();
            ViewData["OtherInstrumentID"] = ViewData["InstrumentID"];

            //Toggle the Open/Closed state of the collapse depending on if we are filtering
            ViewData["Filtering"] = ""; //Assume not filtering
            //Then in each "test" for filtering, add ViewData["Filtering"] = " show" if true;

            //List of sort options.
            //NOTE: make sure this array has matching values to the column headings
            string[] sortOptions = new[] { "Musician", "Phone", "Age", "Primary Instrument" };

            var musicians = _context.Musicians
                .Include(p => p.MusicianThumbnail)
                .Include(m => m.Instrument)
                .Include(d => d.MusicianDocuments)
                .Include(m=>m.Plays).ThenInclude(p => p.Instrument)
                .AsNoTracking();

            //Add as many filters as needed
            if (InstrumentID.HasValue)
            {
                musicians = musicians.Where(p => p.InstrumentID == InstrumentID);
                ViewData["Filtering"] = "btn-danger";
            }
            if (OtherInstrumentID.HasValue)
            {
                musicians = musicians.Where(p => p.Plays.Any(p=>p.InstrumentID == OtherInstrumentID));
                ViewData["Filtering"] = "btn-danger";
            }
            if (!String.IsNullOrEmpty(SearchName))
            {
                musicians = musicians.Where(p => p.LastName.ToUpper().Contains(SearchName.ToUpper())
                                       || p.FirstName.ToUpper().Contains(SearchName.ToUpper()));
                ViewData["Filtering"] = "btn-danger";
            }
            if (!String.IsNullOrEmpty(SearchPhone))
            {
                musicians = musicians.Where(p => p.Phone.ToUpper().Contains(SearchPhone.ToUpper()));
                ViewData["Filtering"] = "btn-danger";
            }
            //Before we sort, see if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted!
            {
                page = 1;//Reset page to start

                if (sortOptions.Contains(actionButton))//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
                else //Sort by the controls in the filter area
                {
                    sortDirection = String.IsNullOrEmpty(sortDirectionCheck) ? "asc" : "desc";
                    sortField = sortFieldID;
                }
            }


            //Now we know which field and direction to sort by
            if (sortField == "Phone")
            {
                if (sortDirection == "asc")
                {
                    musicians = musicians
                        .OrderBy(p => p.Phone)
                        .ThenBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
                else
                {
                    musicians = musicians
                        .OrderByDescending(p => p.Phone)
                        .ThenBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
            }
            else if (sortField == "Age")
            {
                if (sortDirection == "asc")
                {
                    musicians = musicians
                        .OrderByDescending(p => p.DOB)
                        .ThenBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
                else
                {
                    musicians = musicians
                        .OrderBy(p => p.DOB)
                        .ThenBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
            }
            else if (sortField == "Primary Instrument")
            {
                if (sortDirection == "asc")
                {
                    musicians = musicians
                        .OrderBy(p => p.Instrument.Name)
                        .ThenBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
                else
                {
                    musicians = musicians
                        .OrderByDescending(p => p.Instrument.Name)
                        .ThenBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
            }
            else //Sorting by Musician Name
            {
                if (sortDirection == "asc")
                {
                    musicians = musicians
                        .OrderBy(p => p.LastName)
                        .ThenBy(p => p.FirstName);
                }
                else
                {
                    musicians = musicians
                        .OrderByDescending(p => p.LastName)
                        .ThenByDescending(p => p.FirstName);
                }
            }
            //Set sort for next time
            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            //SelectList for Sorting Options
            ViewBag.sortFieldID = new SelectList(sortOptions, sortField.ToString());

            //Handle Paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, "musicians");
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<Musician>.CreateAsync(musicians.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }

        // GET: Musicians/Details/5
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Musicians == null)
            {
                return NotFound();
            }

            var musician = await _context.Musicians
                .Include(p => p.MusicianPhoto)
                //.Include(m => m.Instrument)
                //.Include(d => d.MusicianDocuments)
                //.Include(p => p.Performances)
                //.Include(m => m.Plays).ThenInclude(p => p.Instrument)

                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (musician == null)
            {
                return NotFound();
            }
            
            return View(musician);
        }
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public PartialViewResult ListOfPerformances(int id)
        {
            var query = from s in _context.Performances
                        .Include(p => p.Musician)
                        .ThenInclude(p => p.Instrument)
                        .Include(p => p.Song).ThenInclude(p => p.Album)

                        where s.MusicianID == id
                        select s;
            return PartialView("_ListOfPerformances", query.ToList());
        }

        // GET: Musicians/Create
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public IActionResult Create()
        {
            var musician = new Musician();
            PopulateAssignedPlaysData(musician);
            PopulateDropDownLists();
            return View();
        }

        // POST: Musicians/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public async Task<IActionResult> Create([Bind("FirstName,MiddleName,LastName,Phone,DOB," +
            "SIN,Email,InstrumentID")] Musician musician, string[] selectedOptions, 
            IFormFile thePicture, List<IFormFile> theFiles)
        {
            try
            {
                //Add the selected plays
                if (selectedOptions != null)
                {
                    foreach (var play in selectedOptions)
                    {

MVC_Music/Views/Musicians/Create.cshtml
@model MVC_Music.Models.Musician

@{
    ViewData["Title"] = "Create Musician";
}

<h2>Create Musician</h2>

<hr />
<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label custom-file-label">Picture File:</label>
                <div class="input-group mb-3">
                    <input type="file" class="form-control" name="thePicture" id="thePicture">
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="SIN" class="control-label"></label>
                <input asp-for="SIN" class="form-control" />
                <span asp-validation-for="SIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label custom-file-label">Upload Documents:</label>
                <div class="input-group mb-3">
                    <input type="file" class="form-control" name="theFiles" multiple="multiple">
                </div>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentID" class="control-label"></label>
                <select asp-for="InstrumentID" class="form-control" asp-items="ViewBag.InstrumentID">
                    <option value="">Select the Primary Instrument</option>
                </select>
                <span asp-validation-for="InstrumentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.Plays)</label>
                <div class="col-md-offset-1">
                    <table>
                        <tr>
                            @{
                                int cnt = 0;
                                List<MVC_Music.ViewModels.CheckOptionVM> checkboxes = ViewBag.PlayOptions;
                                foreach (var checkbox in checkboxes)
                                {
                                    if (cnt++ % 2 == 0)
                                    {
                                    @:</tr><tr>
                                    }
                                    @:<td>
                                        <input type="checkbox"
                                               name="selectedOptions"
                                               value="@checkbox.ID"
                                               @(Html.Raw(checkbox.Assigned ? "checked=\"checked\"" : "")) />
                                        @checkbox.DisplayText @:&nbsp;&nbsp;
                                    @:</td>
                                }
                            @:</tr>
                            }
                        </table>
                    </div>
                </div>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div>
    <a href='@ViewData["returnURL"]'>Back to Musician List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

MVC_Music/Views/Musicians/Delete.cshtml
@model MVC_Music.Models.Musician

@{
    ViewData["Title"] = "Delete Musician";
}

<h2>Delete Musician</h2>

<h3>Are you sure you want to delete @Model.FullName?</h3>
<div>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneFormatted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SIN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SINFormatted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instrument)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instrument.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plays)
        </dt>
        <dd class="col-sm-10">
            @{
                int playCount = Model.Plays.Count;
                if (playCount > 0)
                {
                    string firstPlay = Model.Plays.FirstOrDefault().Instrument.Name;
                    if (playCount > 1)
                    {
                        string playList = "";
                        var c = Model.Plays.ToList();
                        for (int i = 1; i < playCount; i++)//Skip the first because we have it already
                        {
                            playList += c[i].Instrument.Name + " <br />";
                        }
                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseHistory@(Model.ID)"
                                aria-expanded="false" aria-controls="collapseHistory@(Model.ID)">
                            @firstPlay <span class="badge bg-info">@playCount</span>
                        </a>
                        <div class="collapse" id="collapseHistory@(Model.ID)">
                            @Html.Raw(playList)
                        </div>
                    }
                    else
                    {
                        @firstPlay
                    }
                }
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a href='@ViewData["returnURL"]'>Back to Musician List</a>
    </form>
</div>

MVC_Music/Views/Musicians/Details.cshtml
@model MVC_Music.Models.Musician

@{
    ViewData["Title"] = "Musician Details";
}

<h2>Musician Details</h2>

<div>
    <hr />
    <figure class="row">
        <p class="col-auto">
                     @{
                if (Model.MusicianPhoto?.Content != null)
                {
                    @:
                        string imageBase64 = Convert.ToBase64String(Model.MusicianPhoto.Content);
                        string imageSrc = string.Format("data:" + Model.MusicianPhoto.MimeType + ";base64,{0}", imageBase64);
                        <img src="@imageSrc" alt="Profile Picture of @Model.FullName" title="Profile Picture of @Model.FullName" class="img-fluid rounded" />
                    @:
                }
            }

        </p>
        
        <figcaption class="col mt-3">
            <dl class="row lh-1">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.MiddleName)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.MiddleName)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Phone)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.PhoneFormatted)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.DOB)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.DOB)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.SIN)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.SINFormatted)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Instrument)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Instrument.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Plays)
                </dt>
                <dd class="col-sm-10">
                    @{
                        int playCount = Model.Plays.Count;
                        if (playCount > 0)
                        {
                            string firstPlay = Model.Plays.FirstOrDefault().Instrument.Name;
                            if (playCount > 1)
                            {
                                string playList = "";
                                var c = Model.Plays.ToList();
                                for (int i = 1; i < playCount; i++)//Skip the first because we have it already
                                {
                                    playList += c[i].Instrument.Name + " <br />";
                                }
                                <a class="" role="button" data-bs-toggle="collapse" href="#collapseHistory@(Model.ID)"
                                        aria-expanded="false" aria-controls="collapseHistory@(Model.ID)">
                                    @firstPlay <span class="badge bg-info">@playCount</span>
                                </a>
                                <div class="collapse" id="collapseHistory@(Model.ID)">
                                    @Html.Raw(playList)
                                </div>
                            }
                            else
                            {
                                @firstPlay
                            }
                        }
                    }
                </dd>        

            </dl>
        </figcaption>
    
    </figure>
    <hr />       

    <dl class="row">
        <dt class="col-sm-2">
            Performances
        </dt>
        <dd class="col-sm-10">
            <div id="performances">Performance List</div>
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a href='@ViewData["returnURL"]'>Back to Musician List</a>
</div>

@section Scripts {
    <script type="text/javascript">
       $('#performances').load('/Musicians/ListOfPerformances/@Model.ID');
    </script>
}

MVC_Music/Views/Musicians/PerformanceSummary.cshtml
@model IEnumerable<MVC_Music.ViewModels.PerformanceSummaryVM>

@{
    ViewData["Title"] = "Performance Summary";
}

<h2>PerformanceSummary</h2>

<a asp-action="DownloadPerformanceSummary" class="btn btn-info float-end">Download Performance Summary Report</a>
 
<form asp-controller="Musicians" asp-action="PerformanceSummary" method="get">

    
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
            
                <th>
                    @Html.DisplayNameFor(model => model.NumberOfPerformances)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AverageFeePaid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HighestFeePaid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LowestFeePaid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberOfSongs)
                </th>
            
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
           
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfPerformances)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AverageFeePaid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HighestFeePaid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LowestFeePaid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfSongs)
                </td>
            
            </tr>
    }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>

MVC_Music/Views/Musicians/_ListOfPerformances.cshtml
@model IEnumerable<MVC_Music.Models.Performance>
<br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <h5 class="panel-title"></h5>
    </div>
    <div class="panel-body scrollable-panel">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Album
                    </th>
                    <th>
                        Song
                    </th>
                    <th>
                        Instrument
                    </th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Song.Album.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Song.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Instrument.Name)
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>