MVC_Music/Controllers/SongPerformancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Music.Data;
using MVC_Music.Models;
using MVC_Music.Utilities;

namespace MVC_Music.Controllers
{
    public class SongPerformancesController : CustomControllers.ElephantController
    {
        private readonly MusicContext _context;

        public SongPerformancesController(MusicContext context)
        {
            _context = context;
        }

        // GET: SongPerformances
        public async Task<IActionResult> Index(int? SongID, int? page, int? pageSizeID,
            int? MusicianID, int? InstrumentID, string SearchString, string actionButton, 
            string sortDirection = "desc", string sortField = "Musician")
        {
            //Clear the sort/filter/paging URL Cookie for Controller
            CookieHelper.CookieSet(HttpContext, ControllerName() + "URL", "", -1);

            //Get the URL with the last filter, sort and page parameters from THE SONG Index View
            ViewData["returnURL"] = MaintainURL.ReturnURL(HttpContext, "Songs");

            if (!SongID.HasValue)
            {
                //Go back to the proper return URL for the Patients controller
                return Redirect(ViewData["returnURL"].ToString());
            }

            PopulateDropDownLists();

            //Toggle the Open/Closed state of the collapse depending on if we are filtering
            ViewData["Filtering"] = "btn-outline-dark"; //Asume not filtering
            //Then in each "test" for filtering, add ViewData["Filtering"] = "btn-danger" if true;

            //NOTE: make sure this array has matching values to the column headings
            string[] sortOptions = new[] { "Musician", "Instrument", "Fee Paid" };

            var performances =from p in _context.Performances
                .Include(p => p.Instrument)
                .Include(p => p.Musician)
                .Include(p => p.Song)
                where p.SongID== SongID.GetValueOrDefault()
                select p;

            //Now get the MASTER record, the Song, so it can be displayed at the top of the screen
            var song = await _context.Songs
                .Include(s => s.Album)
                .Include(s => s.Genre)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == SongID.GetValueOrDefault());
            ViewBag.Song = song;

            if (MusicianID.HasValue)
            {
                performances = performances.Where(p => p.MusicianID == MusicianID);
                ViewData["Filtering"] = "btn-danger";
            }
            if (InstrumentID.HasValue)
            {
                performances = performances.Where(p => p.InstrumentID == InstrumentID);
                ViewData["Filtering"] = "btn-danger";
            }
            if (!String.IsNullOrEmpty(SearchString))
            {
                performances = performances.Where(p => p.Comments.ToUpper().Contains(SearchString.ToUpper()));
                ViewData["Filtering"] = "btn-danger";
            }
            //Before we sort, see if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted so lets sort!
            {
                page = 1;//Reset back to first page when sorting or filtering

                if (sortOptions.Contains(actionButton))//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            //Now we know which field and direction to sort by.
            if (sortField == "Instrument")
            {
                if (sortDirection == "asc")
                {
                    performances = performances
                        .OrderBy(p => p.Instrument.Name)
                        .ThenBy(p => p.Musician.LastName)
                        .ThenBy(p => p.Musician.FirstName); 
                }
                else
                {
                    performances = performances
                        .OrderByDescending(p => p.Instrument.Name)
                        .ThenBy(p => p.Musician.LastName)
                        .ThenBy(p => p.Musician.FirstName);
                }
            }
            else if (sortField == "Fee Paid")
            {
                if (sortDirection == "asc")
                {
                    performances = performances
                        .OrderBy(p => p.FeePaid)
                        .ThenBy(p => p.Musician.LastName)
                        .ThenBy(p => p.Musician.FirstName);
                }
                else
                {
                    performances = performances
                        .OrderByDescending(p => p.FeePaid)
                        .ThenBy(p => p.Musician.LastName)
                        .ThenBy(p => p.Musician.FirstName);
                }
            }
            else //Musician
            {
                if (sortDirection == "asc")
                {
                    performances = performances
                        .OrderBy(p => p.Musician.LastName)
                        .ThenBy(p => p.Musician.FirstName);
                }
                else
                {
                    performances = performances
                        .OrderByDescending(p => p.Musician.LastName)
                        .ThenByDescending(p => p.Musician.FirstName);
                }
            }
            //Set sort for next time
            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            //Handle Paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, ControllerName());
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);

            var pagedData = await PaginatedList<Performance>.CreateAsync(performances.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }

        // GET: Performances/Add
        public IActionResult Add(int? SongID, string SongTitle)
        {

            if (!SongID.HasValue)
            {
                return Redirect(ViewData["returnURL"].ToString());
            }
            ViewData["SongTitle"] = SongTitle;

            Performance a = new()
            {
                SongID = SongID.GetValueOrDefault()
            };

            PopulateDropDownLists();
            return View(a);
        }

        // POST: Performances/Add
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("ID,MusicianID,InstrumentID,Comments," +
            "FeePaid,SongID")] Performance performance, string SongTitle)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(performance);
                    await _context.SaveChangesAsync();
                    return Redirect(ViewData["returnURL"].ToString());
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to add performance. Try again, and if the problem " +
                    "persists see your system administrator.");
            }

            PopulateDropDownLists(performance);
            ViewData["SongTitle"] = SongTitle;
            return View(performance);
        }

        // GET: SongPerformance/Update/5
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances
               .Include(a => a.Musician)
               .Include(a => a.Instrument)
               .Include(a => a.Song)
               .AsNoTracking()
               .FirstOrDefaultAsync(m => m.ID == id);
            if (performance == null)
            {
                return NotFound();
            }
            PopulateDropDownLists(performance);
            return View(performance);
        }

        // POST: SongPerformance/Update/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            var performanceToUpdate = await _context.Performances
               .Include(a => a.Musician)
               .Include(a => a.Instrument)
               .Include(a => a.Song)
               .FirstOrDefaultAsync(m => m.ID == id);

            //Check that you got it or exit with a not found error
            if (performanceToUpdate == null)
            {
                return NotFound();
            }

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<Performance>(performanceToUpdate, "",
                p => p.Comments, p => p.MusicianID, p => p.FeePaid, p => p.InstrumentID))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return Redirect(ViewData["returnURL"].ToString());
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformanceExists(performanceToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else

MVC_Music/Views/SongPerformances/Add.cshtml
@model MVC_Music.Models.Performance

@{
    ViewData["Title"] = "Add Performance";
}

<h2>Add Performance on Song: @ViewData["SongTitle"]</h2>
<hr />

<form asp-action="Add">
    <input type="hidden" name="SongID" value="@Model.SongID" />
    <input type="hidden" name="SongTitle" value="@ViewData[" SongTitle"]" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="MusicianID" class="control-label"></label>
                <select asp-for="MusicianID" class="form-control" asp-items="ViewBag.MusicianID">
                    <option value="">Select the Musician</option>
                </select>
                <span asp-validation-for="MusicianID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentID" class="control-label"></label>
                <select asp-for="InstrumentID" class="form-control" asp-items="ViewBag.InstrumentID">
                    <option value="">Select the Instrument</option>
                </select>
                <span asp-validation-for="InstrumentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FeePaid" class="control-label"></label>
                <input asp-for="FeePaid" class="form-control" />
                <span asp-validation-for="FeePaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea asp-for="Comments" class="form-control" rows="6"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a href='@ViewData["returnURL"]'>Back to Song</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC_Music/Views/SongPerformances/Index.cshtml
@model IEnumerable<MVC_Music.Models.Performance>

@{
    ViewData["Title"] = "Song Performances";
    MVC_Music.Models.Song song = (MVC_Music.Models.Song)ViewBag.Song;
}
<h2>Performance Details for Song: <strong>@song.Title</strong></h2>
<hr/>
<div class="row">
    <div class="col-6">
        <dl class="row">
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => song.DateRecorded)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => song.DateRecorded)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => song.Album)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => song.Album.Name)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => song.Genre)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => song.Genre.Name)
            </dd>
        </dl>
    </div>
</div>
<form asp-action="Index" method="get">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
    <input type="hidden" name="SongID" value="@song.ID" />
    <div class="form-horizontal">
        <button class="btn @(ViewData["Filtering"])" type="button" data-bs-toggle="collapse" id="filterToggle" data-bs-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
            Filter Performances
        </button>
        <div class="form-horizontal">
            <div class="collapse card card-body bg-light" style="padding-top: 10px; padding-bottom: 5px;" id="collapseFilter">
                <div class="row">
                    <div class="form-group col-md-3 ml-md-3">
                        <label class="control-label">By Musician:</label>
                        @Html.DropDownList("MusicianID", null, "All Musicians", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-3 ml-md-3">
                        <label class="control-label">By Instrument:</label>
                        @Html.DropDownList("InstrumentID", null, "All Instruments", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-3">
                        <label class="control-label">Search Comments:</label>
                        @Html.TextBox("SearchString", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-3 align-self-end">
                        <input type="submit" name="actionButton" value="Apply" class="btn btn-primary" />
                        <a asp-action="Index" asp-route-SongID="@song.ID">Clear</a>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <table class="table">
                <colgroup>
                    <col span="1" />
                    <col span="1" />
                    <col span="1" />
                    <col span="1" width="400" />
                    <col span="1" />
                </colgroup>
                <thead>
                    <tr>
                        <th>
                            <input type="submit" name="actionButton" value="Musician" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Instrument" class="btn btn-link" />
                        </th>
                        <td>
                            <input type="submit" name="actionButton" value="Fee Paid" class="btn btn-link" />
                            @{
                                double totalFees = 0d;
                            }
                        </td>
                        <th>
                            <input type="submit" disabled="disabled" value="Comments" class="btn btn-link" />
                        </th>
                        <th>
                            <a asp-controller="SongPerformances" asp-action="Add" asp-route-SongID="@song.ID"
                               asp-route-SongTitle="@song.Title">
                                <span class="btn btn-success" data-bs-toggle="tooltip"
                                      title="Add Appointment"><strong>&#x271A; Add</strong></span>
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Musician.FormalName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Instrument.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FeePaid)
                                @{
                                    totalFees += item.FeePaid;
                                }
                            </td>
                            <td>
                                @{
                                    string[] noteWords = item.Comments.Split(' ');
                                    if (noteWords.Count() > 5)
                                    {
                                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseSum@(item.ID)" aria-expanded="false" aria-controls="collapseSum@(item.ID)">
                                            @(string.Join(" ", noteWords.Take(5)) + "...")
                                        </a>
                                        <div class="collapse" id="collapseSum@(item.ID)">
                                            <div class="well">
                                                @(string.Join(" ", noteWords.Skip(5)))
                                            </div>
                                        </div>
                                    }
                                    else
                                    {
                                        @item.Comments
                                    }
                                }
                            </td>
                            <td>
                                <a asp-controller="SongPerformances" asp-action="Update" asp-route-id="@item.ID">
                                    <span class="btn btn-sm btn-outline-primary" data-bs-toggle="tooltip" title="Edit Performance">&#x270D;</span>
                                </a>
                                <a asp-controller="SongPerformances" asp-action="Remove" asp-route-id="@item.ID">
                                    <span class="btn btn-sm btn-outline-danger" data-bs-toggle="tooltip" title="Delete Performance">&#x274C;</span>
                                </a>
                            </td>
                        </tr>
                    }
                    <tr>
                    <td></td>
                    <td align="right">
                        Total Fees Paid:
                    </td>
                    <td>
                        <strong>@totalFees.ToString("c")</strong>
                    </td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <partial name="_PagingNavBar" />
</form>
<div>
    <a asp-action="Edit" asp-controller="Songs" asp-route-id="@song.ID">Edit</a> |
    <a href='@ViewData["returnURL"]'>Back to Song List</a>
</div>

MVC_Music/Views/SongPerformances/Remove.cshtml
@model MVC_Music.Models.Performance

@{
    ViewData["Title"] = "Remove Performance";
}

<h2>Remove Performance on Song: @Model.Song.Title</h2>

<h3>Are you sure you want to delete this Performance?</h3>
<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Musician)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Musician.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instrument)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instrument.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FeePaid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FeePaid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Remove" class="btn btn-danger" /> |
        <a href='@ViewData["returnURL"]'>Back to Song</a>
    </form>
</div>

MVC_Music/Views/SongPerformances/Update.cshtml
@model MVC_Music.Models.Performance

@{
    ViewData["Title"] = "Update Performance";
}

<h2>Update Performance on Song:  @Model.Song.Title</h2>

<hr />
<form asp-action="Update">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
    <input type="hidden" name="SongID" value="@Model.SongID" />
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="MusicianID" class="control-label"></label>
                <select asp-for="MusicianID" class="form-control" asp-items="ViewBag.MusicianID"></select>
                <span asp-validation-for="MusicianID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentID" class="control-label"></label>
                <select asp-for="InstrumentID" class="form-control" asp-items="ViewBag.InstrumentID"></select>
                <span asp-validation-for="InstrumentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FeePaid" class="control-label"></label>
                <input asp-for="FeePaid" class="form-control" />
                <span asp-validation-for="FeePaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea asp-for="Comments" class="form-control" rows="6"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a href='@ViewData["returnURL"]'>Back to Song</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}