MVC_Music/Models/Instrument.cs
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Xml.Linq;
using System.Security.AccessControl;

namespace MVC_Music.Models
{
    public class Instrument : Auditable
    {
        public int ID { get; set; }

        [Display(Name = "Instrument")]
        [Required(ErrorMessage = "You cannot leave the name of the Instrument blank.")]
        [StringLength(50, ErrorMessage = "Instrument name cannot be more than 50 characters long.")]
        public string Name { get; set; }

        [Display(Name = "Primary Musicians")]
        public ICollection<Musician> Musicians { get; set; } = new HashSet<Musician>();

        [Display(Name = "Other Musicians")]
        public ICollection<Play> Plays { get; set; } = new HashSet<Play>();

        
        public ICollection<Performance> Performances { get; set; } = new HashSet<Performance>();


    }
}

MVC_Music/Controllers/InstrumentsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Metrics;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using MVC_Music.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using MVC_Music.Data;
using MVC_Music.Models;
using MVC_Music.Utilities;
using OfficeOpenXml;
using Instrument = MVC_Music.Models.Instrument;
using MedicalOffice.ViewModels;

namespace MVC_Music.Controllers
{
    [Authorize]
    public class InstrumentsController : CustomControllers.ElephantController
    {
        private readonly MusicContext _context;

        //for sending email
        private readonly IMyEmailSender _emailSender;

        public InstrumentsController(MusicContext context, IMyEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }


        // GET: Instruments
        public async Task<IActionResult> Index(int? page, int? pageSizeID)
        {
            //Clear the sort/filter/paging URL Cookie for Controller
            CookieHelper.CookieSet(HttpContext, ControllerName() + "URL", "", -1);

            var instruments = _context.Instruments
                .Include(i => i.Musicians)
                .Include(i => i.Plays).ThenInclude(p => p.Musician)
                .OrderBy(i => i.Name)
                .AsNoTracking();

            //Handle Paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, "musicians");
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<Instrument>.CreateAsync(instruments.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }

        // GET: Instruments/Details/5
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Instruments == null)
            {
                return NotFound();
            }

            var instrument = await _context.Instruments
                .Include(i => i.Musicians)
                .Include(i => i.Plays).ThenInclude(p => p.Musician)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (instrument == null)
            {
                return NotFound();
            }

            return View(instrument);
        }

        // GET: Instruments/Create
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public IActionResult Create()
        {
            var instrument = new Instrument();
            PopulatePlaysInstrumentData(instrument);
            return View();
        }

        
        // POST: Instruments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public async Task<IActionResult> Create([Bind("ID,Name")] Instrument instrument, string[] selectedOptions)
        {
            try
            {
                UpdatePlays(selectedOptions, instrument);
                if (ModelState.IsValid)
                {
                    _context.Add(instrument);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", new { instrument.ID });
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            PopulatePlaysInstrumentData(instrument);
            return View(instrument);
        }

        // GET: Instruments/Edit/5
        [Authorize(Roles = "Admin, Supervisor, Staff")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Instruments == null)
            {
                return NotFound();
            }

            var instrument = await _context.Instruments
                .Include(i => i.Plays).ThenInclude(p => p.Musician)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (instrument == null)
            {
                return NotFound();
            }

            if (User.IsInRole("Staff"))
            {
                if (instrument.CreatedBy != User.Identity.Name)
                {
                    ModelState.AddModelError("", "As a Staff, you cannot edit this " +
                        "Musician because you didn't enter them into the system.");
                    ViewData["NoSubmit"] = "disabled=disabled";
                   
                }
            }
            PopulatePlaysInstrumentData(instrument);
            return View(instrument);
        }

        // POST: Instruments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string[] selectedOptions)
        {
            //Go get the Instrument to update
            var instrumentToUpdate = await _context.Instruments
                .Include(i => i.Plays).ThenInclude(p => p.Musician)
                .FirstOrDefaultAsync(m => m.ID == id);

            //Check that you got it or exit with a not found error
            if (instrumentToUpdate == null)
            {
                return NotFound();
            }

            if (User.IsInRole("Staff"))
            {
                if (instrumentToUpdate.CreatedBy != User.Identity.Name)
                {                    
                    ModelState.AddModelError("", "As a Staff, you cannot edit this " +
                        "Musician because you didn't enter them into the system.");
                    return NotFound("You Cannot Edit This Instrument!");
                }
            }

            UpdatePlays(selectedOptions, instrumentToUpdate);

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<Instrument>(instrumentToUpdate, "",
                d => d.Name))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", new { instrumentToUpdate.ID });
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstrumentExists(instrumentToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }

            }

            PopulatePlaysInstrumentData(instrumentToUpdate);
            return View(instrumentToUpdate);
        }

        // GET: Instruments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Instruments == null)
            {
                return NotFound();
            }

            var instrument = await _context.Instruments
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (instrument == null)
            {
                return NotFound();
            }

            return View(instrument);
        }

        // POST: Instruments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Instruments == null)
            {
                return Problem("Entity set 'MusicContext.Instruments'  is null.");
            }
            var instrument = await _context.Instruments
                .FirstOrDefaultAsync(m => m.ID == id);
            try
            {
                if (instrument != null)
                {
                    _context.Instruments.Remove(instrument);
                }
                await _context.SaveChangesAsync();
                return Redirect(ViewData["returnURL"].ToString());
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("FOREIGN KEY constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to Delete Instrument. Remember, you cannot delete an Instrument that any Musician plays.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(instrument);
        }

        // GET/POST: Instruments/Notification/5

MVC_Music/Views/Instruments/Create.cshtml
@model MVC_Music.Models.Instrument

@{
    ViewData["Title"] = "Create Instrument";
}

<h2>Create Instrument</h2>

<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" id="btnSubmit" class="btn btn-primary" />
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label"> Musicians who Play</label> <button type="button" id="btnRight" class="btn btn-danger btn-sm">
                        <strong>-</strong>
                    </button>
                    @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @size = 10, @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label"> Choose Musicians</label> <button type="button" id="btnLeft" class="btn btn-success btn-sm">
                        <strong>+</strong>
                    </button>
                    @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @size = 10, @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
</form>

<div>
    <a href='@ViewData["returnURL"]'>Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/multiselect.js"></script>
}

MVC_Music/Views/Instruments/Delete.cshtml
@model MVC_Music.Models.Instrument

@{
    ViewData["Title"] = "Delete Instrument";
}

<h2>Delete Instrument</h2>

<h3>Are you sure you want to delete @Model.Name?</h3>
<div>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a href='@ViewData["returnURL"]'>Back to List</a>
    </form>
</div>

MVC_Music/Views/Instruments/Details.cshtml
@model MVC_Music.Models.Instrument

@{
    ViewData["Title"] = "Instrument Details";
}

<h2>Instrument Details</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Musicians)
        </dt>
        <dd class="col-sm-10">
            @{
                int musicianCount = Model.Musicians.Count;
                if (musicianCount > 0)
                {
                    string firstMusician = Model.Musicians.FirstOrDefault().FullName;
                    if (musicianCount > 1)
                    {
                        string musicianList = "";
                        var c = Model.Musicians.ToList();
                        for (int i = 1; i < musicianCount; i++)//Skip the first because we have it already
                        {
                            musicianList += c[i].FullName + " <br />";
                        }
                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseMusicians@(Model.ID)"
                   aria-expanded="false" aria-controls="collapseMusicians@(Model.ID)">
                            @firstMusician <span class="badge bg-info">@musicianCount</span>
                        </a>
                        <div class="collapse" id="collapseMusicians@(Model.ID)">
                            @Html.Raw(musicianList)
                        </div>
                    }
                    else
                    {
                        @firstMusician
                    }
                }
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plays)
        </dt>
        <dd class="col-sm-10">
            @{
                int playCount = Model.Plays.Count;
                if (playCount > 0)
                {
                    string firstPlay = Model.Plays.FirstOrDefault().Musician.FullName;
                    if (playCount > 1)
                    {
                        string playList = "";
                        var c = Model.Plays.ToList();
                        for (int i = 1; i < playCount; i++)//Skip the first because we have it already
                        {
                            playList += c[i].Musician.FullName + " <br />";
                        }
                        <a class="" role="button" data-bs-toggle="collapse" href="#collapseOther@(Model.ID)"
                   aria-expanded="false" aria-controls="collapseOther@(Model.ID)">
                            @firstPlay <span class="badge bg-info">@playCount</span>
                        </a>
                        <div class="collapse" id="collapseOther@(Model.ID)">
                            @Html.Raw(playList)
                        </div>
                    }
                    else
                    {
                        @firstPlay
                    }
                }
            }
        </dd>
    </dl>
</div>
<div>
    <span style="color:darkgreen">
        This email will send to musicians who has selected as primary instrument!

    </span>

    <a asp-action="Notification" asp-route-id="@Model?.ID" class="linkClick">Send Email Notification</a>
    <br />
    <hr />

    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a href='@ViewData["returnURL"]'>Back to List</a>
</div>

MVC_Music/Views/Instruments/Edit.cshtml
@model MVC_Music.Models.Instrument

@{
    ViewData["Title"] = "Edit Instrument";
}

<h2>Edit Instrument</h2>

<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" @ViewData["NoSubmit"] value="Save" id="btnSubmit" class="btn btn-primary" />
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label"> Musicians who Play</label> <button type="button" id="btnRight" class="btn btn-danger btn-sm">
                        <strong>-</strong>
                    </button>
                    @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @size = 10, @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label"> Choose Musicians</label> <button type="button" id="btnLeft" class="btn btn-success btn-sm">
                        <strong>+</strong>
                    </button>
                    @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @size = 10, @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
</form>

<div>
    <a href='@ViewData["returnURL"]'>Back to Instrument List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/multiselect.js"></script>
}

MVC_Music/Views/Instruments/Index.cshtml
@model IEnumerable<MVC_Music.Models.Instrument>

@{
    ViewData["Title"] = "Instruments Index";
}

<h2>Instruments</h2>

<p>
    
    <a asp-action="Create">Create New</a>
    <form asp-action="InsertFromExcel" asp-controller="Instruments" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label custom-file-label">Upload Excel File:</label>
                    <div class="input-group mb-3">
                        <input type="file" class="form-control" name="theExcel" id="theExcel">
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload Data" class="btn btn-primary" />                   

                </div>
            </div>
        </div>
    </form>
</p>
<form asp-action="Index" method="get">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Musicians)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Plays)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @{
                            int musicianCount = item.Musicians.Count;
                            if (musicianCount > 0)
                            {
                                string firstMusician = item.Musicians.FirstOrDefault().FullName;
                                if (musicianCount > 1)
                                {
                                    string musicianList = "";
                                    var c = item.Musicians.ToList();
                                    for (int i = 1; i < musicianCount; i++)//Skip the first because we have it already
                                    {
                                        musicianList += c[i].FullName + " <br />";
                                    }
                                    <a class="" role="button" data-bs-toggle="collapse" href="#collapseMusicians@(item.ID)"
                           aria-expanded="false" aria-controls="collapseMusicians@(item.ID)">
                                        @firstMusician <span class="badge bg-info">@musicianCount</span>
                                    </a>
                                    <div class="collapse" id="collapseMusicians@(item.ID)">
                                        @Html.Raw(musicianList)
                                    </div>
                                }
                                else
                                {
                                    @firstMusician
                                }
                            }
                        }
                    </td>
                    <td>
                        @{
                            int playCount = item.Plays.Count;
                            if (playCount > 0)
                            {
                                string firstPlay = item.Plays.FirstOrDefault().Musician.FullName;
                                if (playCount > 1)
                                {
                                    string playList = "";
                                    var c = item.Plays.ToList();
                                    for (int i = 1; i < playCount; i++)//Skip the first because we have it already
                                    {
                                        playList += c[i].Musician.FullName +" <br />";
                                    }
                                    <a class="" role="button" data-bs-toggle="collapse" href="#collapseOther@(item.ID)"
                           aria-expanded="false" aria-controls="collapseOther@(item.ID)">
                                        @firstPlay <span class="badge bg-info">@playCount</span>
                                    </a>
                                    <div class="collapse" id="collapseOther@(item.ID)">
                                        @Html.Raw(playList)
                                    </div>
                                }
                                else
                                {
                                    @firstPlay
                                }
                            }
                        }
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>

MVC_Music/Views/Instruments/Notification.cshtml
@model IEnumerable<MVC_Music.Models.Instrument>

@{
    ViewData["Title"] = "Notification Email";
}

<h1>Notification Email</h1>

<h2>Message to Patients in @ViewData["InstrumentName"]</h2>

<hr />
<form asp-action="Notification">
    <div class="row">
        <div class="col-md-8">
            <div class="text-danger">@ViewData["Message"]</div>
            <hr />
            <input type="hidden" name="id" value="@ViewData["id"]" />
            <input type="hidden" name="Instrument" value="@ViewData["InstrumentName"]" />
            <div class="form-group">
                <label for="Subject" class="control-label">Email Subject</label>
                <input type="text" id="Subject" name="Subject" class="form-control" />
            </div>
            <div class="form-group">
                <label for="emailContent" class="control-label">Message Content</label>
                <textarea id="emailContent" name="emailContent" rows="5" cols="40" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary" />
            </div>

        </div>
    </div>
</form>
<div>
    <a asp-action="Index" asp-controller="Instruments"> Back to Instrument List</a>
</div>